codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error

    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/**"
  - "experiments/**"
  - "scripts/**"
  - "**/__pycache__"
  - "**/*.pyc"
  - "**/__init__.py"
